[veggies]
leek
mushrooms
lemon|lemons
garlic clove|garlic cloves
ginger
red onion|red onions

[grocery]
madame loik echalote
sugar

[spices]
curry powder
sichuan peppercorns
star anise
cloves
cinnamon
black cardamom pod|black cardamom pods
green cardamom pod|green cardamom pods
fennel seeds
bay leaves
timut pepper
dried orange peel
MSG
gochugaru
sesame seeds

[other]
oil
salt
mustard

[chinaman]
soy sauce
black vinegar
peanut oil
green onion|green onions
