[butcher]
chicken thigh|chicken thighs


[veggies]
cucumber
leek
mushrooms
lemon|lemons
garlic clove|garlic cloves
ginger
red onion|red onions
hot pepper|hot peppers

[grocery]
madame loik echalote
sugar

[spices]
curry powder
sichuan peppercorns
star anise
cloves
cinnamon
black cardamom pod|black cardamom pods
green cardamom pod|green cardamom pods
fennel seeds
bay leaves
timut pepper
dried orange peel
MSG
gochugaru
sesame seeds
turmeric

[other]
oil
salt
mustard
chicken stock
chili oil
sichuan peppercorn oil

[chinaman]
soy sauce
black vinegar
peanut oil
green onion|green onions
sesame oil
sesame paste
shaoxing wine
peanuts
